version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - run:
          name: send message to sukki bot
          command: |
            git clone --bare https://github.com/sukki/sukki-quant.git ~/sukki-quant-bare
            cd ~/sukki-quant-bare
            git log -n 1 --pretty=format:"[ %h ] %ai %n %s %n %n %b %n https://github.com/sukki/sukki-quant/commit/%H" > git_log
            value=`cat git_log`
            curl -s -X POST https://api.telegram.org/bot539671764:AAH8TATXc3Jm84foXN_sQwYa5gXP59jUinY/sendMessage -d chat_id=-248535918 -d text="$value"