version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - run:
          name: send message to sukki bot
          command: |
            git clone --bare git@github.com:sukki/sukki-quant.git
            cd sukki-quant
            git log -n 1 --pretty=format:'%h,%an,%ar,%s' > git_log
            value=`cat git_log`
            curl -s -X POST https://api.telegram.org/bot539671764:AAH8TATXc3Jm84foXN_sQwYa5gXP59jUinY/sendMessage -d chat_id=-248535918 -d text="$value"